before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
branches:
  only:
    - master
    - /^v\d+(\.\d+){0,2}$/
cache:
  yarn: true
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
language: node_js
notifications:
  email:
    on_failure: always
    on_success: change
