module.exports = {
    'next/google-font-display': 'error',
    'next/google-font-preconnect': 'error',
    'next/inline-script-id': 'error',
    'next/link-passhref': 'error',
    'next/next-script-for-ga': 'error',
    'next/no-css-tags': 'error',
    'next/no-document-import-in-page': 'error',
    'next/no-duplicate-head': 'error',
    'next/no-head-import-in-document': 'error',
    'next/no-html-link-for-pages': 'error',
    'next/no-img-element': 'error',
    'next/no-page-custom-font': 'error',
    'next/no-script-in-document': 'error',
    'next/no-script-in-head': 'error',
    'next/no-server-import-in-page': 'error',
    'next/no-sync-scripts': 'error',
    'next/no-title-in-document-head': 'error',
    'next/no-typos': 'error',
    'next/no-unwanted-polyfillio': 'error',
};
